// Generated by CoffeeScript 1.3.3

/*
 * Copyright 2012 Sven Reissmann <sven@0x80.io>
 *
 * This file is part of pyLogView. It is licensed under the terms of the
 * GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {

  this.Defaults = (function() {

    function Defaults() {}

    Defaults.severity = ["Emerge", "Alert", "Critical", "Error", "Warning", "Notice", "Info", "Debug"];

    Defaults.facility = ["kern", "user", "mail", "daemons", "auth", "syslog", "lpr", "news", "uucp", "cron", "security", "ftp", "ntp", "logaudit", "logalert", "clock", "local0", "local1", "local2", "local3", "local4", "local5", "local6", "local7"];

    return Defaults;

  })();

}).call(this);
