// Generated by CoffeeScript 1.3.3

/*
Copyright 2012 Sven Reissmann <sven@0x80.io>

This file is part of pyLogView. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {
  var EventListModel, EventModel, evlist,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    _this = this;

  EventModel = (function() {

    function EventModel(data) {
      this.id = data._id;
      this.timegenerated = data._source.timegenerated;
      this.timereported = data._source.timereported;
      this.facility = data._source.facility;
      this.severity = data._source.severity;
      this.detail_url = "/event/" + data._id;
      this.host = data._source.hostname;
      this.tag = data._source.tag;
      this.message = data._source.message;
    }

    return EventModel;

  })();

  EventListModel = (function() {

    function EventListModel() {
      this.setFacilityText = __bind(this.setFacilityText, this);

      this.setSeverityText = __bind(this.setSeverityText, this);
      this.events = ko.observableArray([]);
      this.loading = ko.observable(false);
      this.filterSeverity = ko.observable(null);
      this.filterFacility = ko.observable(null);
    }

    EventListModel.prototype.setSeverityText = function(el) {
      this.filterSeverity(Defaults.severity[el.severity]);
      return evlist.loadEvents();
    };

    EventListModel.prototype.setFacilityText = function(el) {
      this.filterFacility(Defaults.facility[el.facility]);
      return evlist.loadEvents();
    };

    EventListModel.prototype.getFilters = function() {
      var result,
        _this = this;
      result = {};
      $('.filter').each(function(index, element) {
        if ($(element).val() !== "") {
          return result[$(element).attr('name')] = $(element).val();
        }
      });
      if (JSON.stringify(result) === "{}") {
        return {
          "match_all": {}
        };
      } else {
        return {
          "prefix": result
        };
      }
    };

    EventListModel.prototype.loadEvents = function() {
      var es_query,
        _this = this;
      es_query = {
        "query": evlist.getFilters(),
        "facets": {
          "range1": {
            "range": {
              "field": "timereported",
              "ranges": [
                {
                  "from": 2012,
                  "to": 2012
                }
              ]
            }
          },
          "histo1": {
            "date_histogram": {
              "field": "timereported",
              "interval": "3h"
            }
          }
        },
        "from": 0,
        "size": 50,
        "sort": []
      };
      return $.ajax({
        url: $('#filterform').attr('action'),
        type: 'POST',
        contentType: "application/json",
        data: JSON.stringify(es_query),
        dataType: 'json',
        beforeSend: function() {
          return _this.loading(true);
        },
        success: function(result) {
          var event;
          _this.events((function() {
            var _i, _len, _ref, _results;
            _ref = result.hits.hits;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              event = _ref[_i];
              _results.push(new EventModel(event));
            }
            return _results;
          })());
          evlist.timeSeries(result.facets.histo1.entries);
          return _this.loading(false);
        }
      });
    };

    EventListModel.prototype.timeSeries = function(data) {
      var chart;
      chart = nv.models.multiBarTimeSeriesChart().x(function(d) {
        return d.time;
      }).y(function(d) {
        return d.count;
      });
      chart.xAxis.tickFormat(function(d) {
        return d3.time.format('%x')(new Date(d));
      }).rotateLabels(-45);
      chart.yAxis.tickFormat(d3.format(',.0f'));
      chart.tooltip = function(key, x, y, e, graph) {
        return "<h3>" + key + "</h3><p>" + y + " during " + x + "</p>";
      };
      d3.select('#timeSeries svg').datum([
        {
          "key": "events",
          "values": data
        }
      ]).transition().duration(100).call(chart);
      return nv.utils.windowResize(chart.update);
    };

    return EventListModel;

  })();

  $('#filterform').bind('keyup', function(event) {
    return evlist.loadEvents();
  });

  $(".clear-addon").each(function(index, element) {
    return $(element).bind('click', function(event) {
      $("#filter_" + $(element).attr("id")).val("");
      return evlist.loadEvents();
    });
  });

  $("#chartdiv").bind('plotselected', function(event) {
    return evlist.loadEvents();
  });

  evlist = new EventListModel;

  evlist.loadEvents();

  ko.applyBindings(evlist);

}).call(this);
