// Generated by CoffeeScript 1.3.3

/*
Copyright 2012 Sven Reissmann <sven@0x80.io>

This file is part of pyLogView. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {
  var EventModel, EventView, view;

  EventModel = (function() {

    function EventModel(data) {
      this.timegenerated = data.timegenerated;
      this.timereported = data.timereported;
      this.facility = data.facility;
      this.severity = data.severity;
      this.host = data.hostname;
      this.tag = data.tag;
      this.message = data.message;
    }

    return EventModel;

  })();

  EventView = (function() {

    function EventView() {
      this.event = ko.observable;
      this.loading = ko.observable(false);
    }

    EventView.prototype.loadEvent = function() {
      var _this = this;
      return $.ajax({
        url: '/_api/get',
        type: 'GET',
        data: 'id=' + $("#event_id").html(),
        beforeSend: function() {
          return _this.loading(true);
        },
        success: function(result) {
          _this.event(new EventModel(result));
          return _this.loading(false);
        }
      });
    };

    return EventView;

  })();

  view = new EventView;

  view.loadEvent();

  ko.applyBindings(view);

}).call(this);
