// Generated by CoffeeScript 1.7.1

/*
Copyright 2013 Sven Reissmann <sven@0x80.io>

This file is part of LogZen. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  require.config({
    urlArgs: 'v=' + new Date(),
    baseUrl: '/js',
    paths: {
      jquery: 'libs/jquery-2.0.3',
      knockout: 'libs/knockout-3.1.0-debug',
      ko_mapping: 'libs/knockout.mapping-2.4.1-debug',
      pager: 'libs/pager-1.0.1.min',
      bootstrap: 'libs/bootstrap',
      vars: 'vars',
      text: 'libs/text',
      prettyjson: 'libs/pretty_json',
      humanize: 'libs/jquery.humanize',
      gridster: 'libs/jquery.gridster'
    },
    shim: {
      'bootstrap': {
        deps: ['jquery']
      },
      'humanize': {
        deps: ['jquery']
      },
      'quickflip': {
        deps: ['jquery']
      },
      'gridster': {
        deps: ['jquery']
      },
      'ko_mapping': {
        deps: ['knockout']
      }
    }
  });

  this.requireVM = function(module) {
    return function(callback) {
      return require(["/pages/" + module + "/model.js"], function(vm) {
        return callback(new vm);
      });
    };
  };

  this.requireHTML = function(module) {
    return function(page, callback) {
      return require(["text!/pages/" + module + "/view.html"], function(html) {
        $(page.element).html(html);
        return callback();
      });
    };
  };

  require(['jquery', 'knockout', 'pager', 'bootstrap', 'prettyjson'], function($, ko, pager) {
    var VM, vm;
    VM = (function() {
      function VM() {
        this.add_evlist = __bind(this.add_evlist, this);
        this.remove_evlist = __bind(this.remove_evlist, this);
        this.isLoggedIn = __bind(this.isLoggedIn, this);
        this.loading = ko.observable(false);
        this.configured = ko.observable(false);
        this.ui_displayMainMenu = ko.computed((function(_this) {
          return function() {
            return _this.configured() === true && _this.username() !== "";
          };
        })(this));
        this.username = ko.observable("");
        this.evlists = ko.observableArray([
          {
            id: +(new Date()),
            title: ko.observable('Eventlist')
          }
        ]);
      }

      VM.prototype.isLoggedIn = function(page, route, callback) {
        return $.ajax({
          url: '/_auth/getlogin',
          dataType: 'json',
          success: (function(_this) {
            return function(result) {
              if (result.success === true) {
                _this.username(result.username);
                return callback();
              } else {
                return window.location.href = "/#system/login";
              }
            };
          })(this),
          error: (function(_this) {
            return function(jqXHR, status, error) {
              _this.error(error);
              return window.location.href = "/#system/login";
            };
          })(this)
        });
      };

      VM.prototype.logout = function() {
        return $.ajax({
          url: '/_auth/logout',
          dataType: 'json',
          success: (function(_this) {
            return function(result) {
              return window.location.href = "/";
            };
          })(this)
        });
      };

      VM.prototype.checkInitialConf = function() {
        return $.ajax({
          url: '/_config',
          type: 'GET',
          data: 'key=configured',
          dataType: 'json',
          success: (function(_this) {
            return function(result) {
              return _this.configured(result.value.toLowerCase() === "true");
            };
          })(this)
        });
      };

      VM.prototype.remove_evlist = function(evlist) {
        return this.evlists.remove(evlist);
      };

      VM.prototype.add_evlist = function() {
        return this.evlists.push({
          id: +(new Date()),
          title: ko.observable('New Tab')
        });
      };

      return VM;

    })();
    vm = new VM;
    pager.extendWithPage(vm);
    ko.applyBindings(vm);
    vm.checkInitialConf();
    pager.onBindingError.add(function(event) {
      var page;
      console.log(event);
      page = event.page;
      return $(page.element).empty().append('<div class="alert"> Error Loading Page</div>');
    });
    return pager.start();
  });

}).call(this);
