// Generated by CoffeeScript 1.6.3
/*
 * Copyright 2012 Sven Reissmann <sven@0x80.io>
 *
 * This file is part of pyLogView. It is licensed under the terms of the
 * GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {
  define([], function() {
    return {
      severity: ["emerge", "alert", "critical", "error", "warning", "notice", "info", "debug"],
      facility: ["kern", "user", "mail", "daemons", "auth", "syslog", "lpr", "news", "uucp", "cron", "security", "ftp", "ntp", "logaudit", "logalert", "clock", "local0", "local1", "local2", "local3", "local4", "local5", "local6", "local7"]
    };
  });

}).call(this);
