// Generated by CoffeeScript 1.7.1

/*
Copyright 2013 Sven Reissmann <sven@0x80.io>

This file is part of LogZen. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
 */

(function() {
  define(['jquery', 'knockout', 'pager', 'bootstrap'], function($, ko, pager) {
    var LoginModel;
    LoginModel = (function() {
      function LoginModel() {
        this.username = ko.observable("");
        this.password = ko.observable("");
        this.submitOK = ko.computed((function(_this) {
          return function() {
            if (_this.username() !== "" && _this.password() !== "") {
              return true;
            } else {
              return false;
            }
          };
        })(this));
      }

      LoginModel.prototype.login = function() {
        return $.ajax({
          url: '/_auth/login',
          type: 'POST',
          data: 'username=' + this.username() + '&password=' + this.password(),
          dataType: 'json',
          success: (function(_this) {
            return function(result) {
              if (result.success === 'true') {
                _this.username(result.username);
                return window.location.href = "/";
              }
            };
          })(this)
        });
      };

      return LoginModel;

    })();
    return LoginModel;
  });

}).call(this);
