// Generated by CoffeeScript 1.6.3
/*
Copyright 2013 Sven Reissmann <sven@0x80.io>

This file is part of LogZen. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {
  define(['jquery', 'knockout', 'pager', 'bootstrap'], function($, ko, pager) {
    var LoginModel;
    LoginModel = (function() {
      function LoginModel() {
        var _this = this;
        this.username = ko.observable("");
        this.password = ko.observable("");
        this.submitOK = ko.computed(function() {
          if (_this.username() !== "" && _this.password() !== "") {
            return true;
          } else {
            return false;
          }
        });
      }

      LoginModel.prototype.login = function() {
        var _this = this;
        return $.ajax({
          url: '/_auth/login',
          type: 'POST',
          data: 'username=' + this.username() + '&password=' + this.password(),
          dataType: 'json',
          success: function(result) {
            if (result.success === 'true') {
              _this.username(result.username);
              return window.location.href = "/";
            }
          }
        });
      };

      return LoginModel;

    })();
    return LoginModel;
  });

}).call(this);
